[book]
authors = ["AnkiDroid Open Source Team"]
language = "en"
multilingual = false
src = "src"
title = "AnkiDroid Manual"

[rust]
edition = "2021"

[build]
extra-watch-dirs = ["po"]

[preprocessor.gettext]
after = ["links"]

[output.html]
curly-quotes = true
cname = "docs.ankidroid.org"
additional-css = [
  "theme/css/kbd.css",
  "theme/css/language-picker.css",
  "theme/css/rtl.css",
]
site-url = "/ankidroiddocs/"
git-repository-url = "https://github.com/ankidroid/ankidroiddocs/"
edit-url-template = "https://github.com/ankidroid/ankidroiddocs/edit/main/{path}"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.linkcheck]
optional = true
warning-policy = "warn"
follow-web-links = true
exclude = [
  'microsoft.com',
  'twitter.com',
  'stackexchange.com',
  'https://github.com/open-spaced-repetition/fsrs4anki#add-on-compatibility',
  'support.google.com',
  'reddit.com',
]

[output.html.fold]
enable = true
level = 0

[output.html.search]
use-boolean-and = true
