name: Install mdbook and dependencies

description: Install mdbook with the dependencies we need.

runs:
  using: composite
  steps:
    # The --locked flag is important for reproducible builds.
    - name: Install mdbook
      run: cargo install mdbook --locked --version 0.4.36
      shell: bash

    - name: Install mdbook-i18n-helpers
      run: cargo install mdbook-i18n-helpers --locked --version 0.3.1
      shell: bash

    - name: Install mdbook-toc
      run: cargo install mdbook-toc --locked --version 0.14.2
      shell: bash

    - name: Install mdbook-linkcheck
      run: cargo install mdbook-linkcheck --locked --version 0.7.7
      shell: bash
